image:
  repository: gigpops/be-applet
  pullPolicy: IfNotPresent
  tag: "latest"

nameOverride: ""
fullnameOverride: "be-applet"

podSecurityContext:
  fsGroup: 2000
  runAsNonRoot: true
  runAsUser: 1000

securityContext:
  capabilities:
    drop:
    - ALL

service:
  type: ClusterIP
  port: 80
  containerPort: 8000

ingress:
  enabled: true
  hosts:
    - host: todo-api.apps.127.0.0.1.nip.io
      paths:
        - path: /
          pathType: ImplementationSpecific

resources:
  limits:
      memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

autoscaling:
  enabled: false

disruption:
  enabled: true
  minAvailable: 1

topologySpreadConstraints:
  enabled: true
  maxSkew: 1

configMap:
  enabled: false

secret:
  enabled: false
  secretName: ""

env:
  - name: DATABASE_URL
    valueFrom:
      secretKeyRef:
        name: db-applet-app
        key: uri

initContainers:
  - name: check-db-applet
    image: busybox:stable
    command: ['sh', '-c', 'until nc -z db-applet-rw 5432; do echo "waiting for database...""; sleep 2; done']
