apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: be-applet
  namespace: todo-list
spec:
  provider:
    kubernetes:
      remoteNamespace: todo-list
      server:
        url: "https://kubernetes.default.svc"
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
      auth:
        serviceAccount:
          name: "be-applet"