{{- if .Values.disruption.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "helm-chart.fullname" . }}
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
spec:
  {{- if .Values.disruption.minAvailable }}
  minAvailable: {{ .Values.disruption.minAvailable | default 1 }}
  {{- else if .Values.disruption.maxUnavailable }}
  maxUnavailable: {{ .Values.disruption.maxUnavailable | default 1 }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "helm-chart.selectorLabels" . | nindent 6 }}
{{- end }}
