apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: external-secrets-operator
  namespace: argocd
  finalizers:
    - argoproj.io/resources-finalizer
spec:
  project: default
  sources:
  - chart: external-secrets
    repoURL: https://charts.external-secrets.io
    targetRevision: 0.19.1
    helm:
      releaseName: external-secrets
      valueFiles:
      - $values/apps/external-secrets-operator/values.yaml

  - repoURL: https://github.com/Lincon-Freitas/devops-tech-challenge
    targetRevision: HEAD
    ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: external-secrets
  syncPolicy:
    automated:
      selfHeal: true
      prune: false
    syncOptions:
      - CreateNamespace=true
      - Replace=true
