apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres-databases
  namespace: argocd
  finalizers:
    - argoproj.io/resources-finalizer
spec:
  project: default
  source:
    repoURL: https://github.com/Lincon-Freitas/devops-tech-challenge
    targetRevision: HEAD
    path: manifests/postgres-databases/
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: todo-list
  syncPolicy:
    automated:
      selfHeal: true
      prune: false
    syncOptions:
      - CreateNamespace=true
