apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
  finalizers:
    - argoproj.io/resources-finalizer
spec:
  project: default
  sources:
  - chart: postgresql
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 16.7.24
    helm:
      releaseName: postgres
      valueFiles:
      - $values/apps/postgres/values.yaml
    
  - repoURL: https://github.com/Lincon-Freitas/devops-tech-challenge
    targetRevision: HEAD
    ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: todo-list
  syncPolicy:
    automated:
      selfHeal: true
      prune: false
    syncOptions:
      - CreateNamespace=true
