apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: postgres
  namespace: argocd
  finalizers:
    - argoproj.io/resources-finalizer
spec:
  project: default
  sources:
  - chart: cloudnative-pg
    repoURL: https://cloudnative-pg.github.io/charts
    targetRevision: 0.25.0
    helm:
      releaseName: postgres
      valueFiles:
      - $values/apps/postgres/values.yaml
    
  - repoURL: https://github.com/Lincon-Freitas/devops-tech-challenge
    targetRevision: ops/argocd-configuration
    ref: values

  destination:
    server: https://kubernetes.default.svc
    namespace: todo-list
  syncPolicy:
    automated:
      selfHeal: true
      prune: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
