apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: fe-applet
  namespace: todo-list
spec:
  podSelector:
    matchLabels:
      app: fe-applet
  policyTypes:
  - Ingress
  - Egress
  ingress:
    - ports:
      - protocol: TCP
        port: 3000
  egress:
    - to:
      - podSelector:
          matchLabels:
            app: be-applet
      ports:
        - protocol: TCP
          port: 8000
  
    - ports:
        - protocol: UDP
          port: 53
        - protocol: TCP
          port: 53
